### ISSUE TITLE
Exception occurs when doing executeBatch() 

### ISSUE THREAD

**Issue by kskim80** [bitnine-oss/agens-graph#164]
Cypher queries are added by addBatch() and do executeBatch().

```java
stmt.addBatch("CREATE (p1:person {name: 'node2'})-[:knows]->(p2:person {name: 'node3'})");
stmt.executeBatch();
```

Then following exceptions are occurred.

```java
java.sql.BatchUpdateException: Batch entry 1 CREATE (p1:person {name: 'node2'})-[:knows]->(p2:person {name: 'node3'}) was aborted.  Call getNextException to see the cause.
java.sql.BatchUpdateException: Batch entry 1 CREATE (p1:person {name: 'node2'})-[:knows]->(p2:person {name: 'node3'}) was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:133)
	at org.postgresql.core.v3.QueryExecutorImpl$ErrorTrackingResultHandler.handleError(QueryExecutorImpl.java:308)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2004)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1187)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1212)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:351)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1019)
	at net.bitnine.graphDB.AgensGraphOps.main(AgensGraphOps.java:91)
	at net.bitnine.graphDB.Run.main(Run.java:19)
```

**Comment by mlogue** [comment]
When I tested it, no exception occurred. Try using the code below to identify the problem.

```java
        try {
            stmt.executeBatch();
        }
        catch (BatchUpdateException e) {
            System.out.println(e.getNextException());
        }
```

**Comment by kskim80** [comment]
In my test program, unique violation occurred. It is a problem of the test program itself.
But I found that when these kinds of error happens, it has another errors that complains 'graph_path' is not set as follows.

```
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "person_name_idx"
  Detail: Key ((properties #>> ARRAY['name'::text]))=(node2) already exists.
elpase time = 631.212 ms
org.postgresql.util.PSQLException: ERROR: graph_path is NULL
  Hint: Use SET graph_path
org.postgresql.util.PSQLException: ERROR: graph_path is NULL
  Hint: Use SET graph_path
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
	at com.bistel.graphDB.AgensGraphOps.main(AgensGraphOps.java:108)
	at com.bistel.graphDB.Run.main(Run.java:19)
```

Why these errors take place?

**Comment by mlogue** [comment]
Please attach the java file used for the test

**Comment by kskim80** [comment]
You can reproduce this Exception easily by making a unique property index and create two nodes with same property value.

**Comment by mlogue** [comment]
I tried to reproduce, but only UNIQUE violation occurs.

A test code:
```sql
create graph u;
create vlabel person;
create elabel knows;
create UNIQUE index on u.person (((properties #>> '{name}'::text[])::text));
```
```java
import java.sql.*;                                                              
                                                                                
public class AgensTest {
    public static void main(String[] args) {
        try {
            String url = "jdbc:agensgraph://localhost:5432/ktlee";
            String usr = "ktlee";

            Class.forName("net.bitnine.agensgraph.Driver");
            Connection conn = DriverManager.getConnection(url, usr, null);

            Statement stmt = conn.createStatement();
            stmt.execute("set graph_path = u");
            stmt.addBatch("CREATE (p1:person {name: 'node2'})-[:knows]->(p2:person {name: 'node3'})");
            stmt.addBatch("CREATE (p1:person {name: 'node2'})-[:knows]->(p2:person {name: 'node3'})");
            try {
                stmt.executeBatch();
            } catch (BatchUpdateException bue) {
                System.out.println(bue.getNextException());
            }
            conn.close();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}
```

**Comment by kskim80** [comment]
It seems like that there's no problem about this.
I closed this issue.
